name: KitPvP
version: 0.1.0
main: eu.iteije.kitpvp.KitPvP
api-version: 1.13
authors: [iTeije]

commands:
  kitpvp:
    usage: /<command>
    description: Krijg een lijst van alle KitPvP commands
  worldtp:
    usage: /<command>
    description: Teleporteer naar een andere wereld